import {useEffect, useRef, useState} from "react";
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Col, Row } from "react-bootstrap";
import DepartureBoard from '../public/js/departure-board';

export default function Home() {
  const tvScreenDisplayRef = useRef();
  const tvScreenContentRef = useRef();
  const gaugeBoardTeam1Ref = useRef();
  const gaugeBoardTeam2Ref = useRef();
  const gaugeBoardTeam3Ref = useRef();
  const gaugeBoardTeam4Ref = useRef();

  const [gaugeBoardTeams, setGaugeBoardTeams] = useState({});

  const scrollDown = (isFirst = false) => {
    let timeoutIdScrollTop;
    if (!isFirst) {
      tvScreenDisplayRef.current.classList.remove(styles.turnOn);
      timeoutIdScrollTop = setTimeout(() => {
        tvScreenDisplayRef.current.classList.add(styles.turnOn);
        tvScreenContentRef.current.scrollTo({
          top: 0,
          behavior: 'instant'
        });
      }, 10000);
    }

    let intervalId;
    const timeoutIdScrollDown = setTimeout(() => {
      intervalId = setInterval(() => {
        if (tvScreenContentRef.current.scrollTop + tvScreenContentRef.current.offsetHeight >= tvScreenContentRef.current.scrollHeight - 5) {
          clearInterval(intervalId);
          return scrollDown();
        }
        tvScreenContentRef.current.scrollTo({
          top: tvScreenContentRef.current.scrollTop + 5,
          behavior: 'smooth'
        });
      }, 100);
    }, isFirst ? 10000 : 20000);

    return { timeoutIdScrollTop, timeoutIdScrollDown, intervalId };
  };

  useEffect(() => {
    const { timeoutIdScrollTop, timeoutIdScrollDown, intervalId } = scrollDown(true);
    return () => {
      if (timeoutIdScrollTop) {
        clearTimeout(timeoutIdScrollTop);
      }
      clearTimeout(timeoutIdScrollDown);
      if (intervalId) {
        clearInterval(intervalId);
      }
    };
  }, []);

  useEffect(() => {
    const teamBoard1 = new DepartureBoard(gaugeBoardTeam1Ref.current, { letterCount: 6 });
    const teamBoard2 = new DepartureBoard(gaugeBoardTeam2Ref.current, { letterCount: 6 });
    const teamBoard3 = new DepartureBoard(gaugeBoardTeam3Ref.current, { letterCount: 6 });
    const teamBoard4 = new DepartureBoard(gaugeBoardTeam4Ref.current, { letterCount: 6 });
    setGaugeBoardTeams({
      teamBoard1,
      teamBoard2,
      teamBoard3,
      teamBoard4,
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Vault-Epitech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Row className="w-100">
          <Col lg={2} className={styles.teamGauges}>
            <div className={styles.teamGauge}>
              <div className={styles.gauge}>
                <div className={`${styles.needle} ${styles.move1}`}></div>
              </div>
              <div ref={gaugeBoardTeam1Ref}></div>
            </div>
            <div className={styles.teamGauge}>
              <div className={styles.gauge}>
                <div className={`${styles.needle} ${styles.move2}`}></div>
              </div>
              <div ref={gaugeBoardTeam2Ref}></div>
            </div>
          </Col>
          <Col lg={8} className={styles.tvContainer}>
            <div className="w-100 position-relative">
              <div className={styles.tvScreen}>
                <div ref={tvScreenDisplayRef} className={`${styles.tvScreenDisplay} ${styles.turnOn}`}>
                  <div className={styles.tvScreenMan}></div>
                  <div ref={tvScreenContentRef} className={styles.tvScreenContent}>
                    <div className="mb-3">
                      <u className="fs-4">25 Derniers evenements:</u>
                    </div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                    <div className="mb-2">- Nom Team: +50 pour "Nettoient la salle cousteau"</div>
                    <div className="mb-2">- Nom Team: +1200 pour "Premier Rush 1"</div>
                  </div>
                </div>
                <div className={styles.tvScreenOverlay}>AV-1</div>
              </div>
              <div className={styles.tvBorder}></div>
            </div>
          </Col>
          <Col lg={2} className={styles.teamGauges}>
            <div className={styles.teamGauge}>
              <div className={styles.gauge}>
                <div className={`${styles.needle} ${styles.move3}`}></div>
              </div>
              <div ref={gaugeBoardTeam3Ref}></div>
            </div>
            <div className={styles.teamGauge}>
              <div className={styles.gauge}>
                <div className={`${styles.needle} ${styles.move4}`}></div>
              </div>
              <div ref={gaugeBoardTeam4Ref}></div>
            </div>
          </Col>
        </Row>
      </main>
    </div>
  )
}
